# Generated by Django 3.2.6 on 2021-08-19 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', models.TextField(max_length=300)),
                ('title', models.CharField(max_length=20)),
                ('image', models.ImageField(upload_to='Portfolio/')),
                ('url', models.URLField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
