# Generated by Django 3.2.6 on 2021-08-20 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_auto_20210819_1013'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('info', models.TextField(max_length=300)),
                ('image', models.ImageField(upload_to='Certificate/')),
                ('course', models.URLField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
